-
  name: wiki2v
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - Wikipedia2VGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: w2v
  controlflow:
    - RunIfNotInstant
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - W2VGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: categories-no-tokenizer
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - CategoriesGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: synonyms
  normalizers:
      - StripEthNormalizer
      - UnicodeNormalizer
      - NamehashNormalizer
      - ReplaceInvalidNormalizer
      - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - WordnetSynonymsGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: on-sale
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - OnSaleMatchGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: permute
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - PermuteGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: prefix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - PrefixGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: suffix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - SuffixGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: substring-normalized
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - LongNameNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - SubstringMatchGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: substring-unnormalized
  normalizers:
    - StripEthNormalizer
    - NamehashNormalizer
    - LongNameNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - SubstringMatchGenerator
  filters:
    - SubnameFilter
-
  name: hyphens
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - HyphenGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: special-char-affix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - SpecialCharacterAffixGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
-
  name: abbreviation
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - AbbreviationGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: flag-affix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - FlagAffixGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
-
  name: leet
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - LeetGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: keycap
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - KeycapGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
#    - ValidNameFilter
-
  name: emoji
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - EmojiGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
-
  name: person-hyphens
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - PersonNameTokenizer
  generators:
    - HyphenGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: person-abbreviation
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - PersonNameTokenizer
  generators:
    - AbbreviationGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter