-
  name: wiki2v
  generator: Wikipedia2VGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 15
    person:
      default: 15
    other:
      default: 15
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.33
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.5
-
  name: w2v
  controlflow:
    - RunIfNotInstant
  generator: W2VGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0.1
      en: 10
    person:
      default: 0.1
    other:
      default: 0
  mode_weights_multiplier:
    instant: 0
    domain_detail: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.33
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.5
-
  name: categories-no-tokenizer
  generator: CategoriesGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 10
    person:
      default: 10
    other:
      default: 10
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
    grouped_instant: 0
    grouped_domain_detail: 0
    grouped_full: 0
  category_limits:
    instant: 0
    domain_detail: 0
    full: 0
-
  name: synonyms
  generator: WordnetSynonymsGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0.1
      en: 5
    person:
      default: 0.1
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.5
-
  name: on-sale
  generator: OnSaleMatchGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  mode_weights_multiplier:
    instant: 0
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: permute
  generator: PermuteGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: prefix
  generator: PrefixGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0.5
      en: 1
    person:
      default: 0
    other:
      default: 0.5
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: suffix
  generator: SuffixGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0.5
      en: 1
    person:
      default: 0
    other:
      default: 0.5
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: substring
  generator: SubstringMatchGenerator
  filters:
    - SubnameFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 1
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  mode_weights_multiplier:
    instant: 0
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: hyphens
  generator: HyphenGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: special-char-affix
  generator: SpecialCharacterAffixGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 1
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: abbreviation
  generator: AbbreviationGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0.1
    person:
      default: 1
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: flag-affix
  generator: FlagAffixGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 1
  mode_weights_multiplier:
    instant: 0.2
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: leet
  generator: LeetGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 1
  mode_weights_multiplier:
    instant: 0
    domain_detail: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 2
-
  name: keycap
  generator: KeycapGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
#    - ValidNameFilter
  weights:
    ngram:
      default: 1
    person:
      default: 1
    other:
      default: 1
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: emoji
  generator: EmojiGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 0.1
      en: 5
    person:
      default: 4
      en: 5
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: person-name-emojify
  generator: PersonNameEmojifyGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 0
    person:
      default: 2
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.1
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: person-name-expand
  generator: PersonNameExpandGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 0
    person:
      default: 3
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.1
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: symbol
  generator: SymbolGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 0.1
      en: 2
    person:
      default: 1
      en: 2
    other:
      default: 0
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
-
  name: collections
  generator: CollectionGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0.1
      en: 10
    person:
      default: 0.1
    other:
      default: 0
  global_limits:
    instant: 0
    domain_detail: 0
    full: 0
    grouped_instant: 0.33
    grouped_domain_detail: 0.33
    grouped_full: 0.33
-
  name: easteregg
  generator: EasterEggGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0
    person:
      default: 0
    other:
      default: 1
  mode_weights_multiplier:
    instant: 0.166
    domain_detail: 0
    full: 0
  global_limits:
    instant: 1
    domain_detail: 0
    full: 0
    grouped_instant: 0
    grouped_domain_detail: 0
    grouped_full: 0
  category_limits:
    instant: 0
    domain_detail: 0
    full: 0
-
  name: reverse
  generator: ReverseGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
  weights:
    ngram:
      default: 0
    person:
      default: 1
    other:
      default: 0
  mode_weights_multiplier:
    instant: 0.166
    domain_detail: 0.1
  global_limits:
    instant: 1
    domain_detail: 1
    full: 1
  category_limits:
    instant: 1
    domain_detail: 1
    full: 1
-
  name: rhymes
  generator: RhymesGenerator
  filters:
    - SubnameFilter
    - ValidNameLengthFilter
  weights:
    ngram:
      default: 0.5
      en: 1
    person:
      default: 0.1
    other:
      default: 0
  mode_weights_multiplier:
    instant: 0.166
    domain_detail: 0.15
    full: 0.5
  global_limits:
    instant: 1
    domain_detail: 1
    full: 0.2
  category_limits:
    instant: 1
    domain_detail: 1
    full: 0.6
