-
  name: wiki2v
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - Wikipedia2VGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: w2v
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - W2VGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: categories-no-tokenizer
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - CategoriesGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: synonyms
  normalizers:
      - StripEthNormalizer
      - UnicodeNormalizer
      - NamehashNormalizer
      - ReplaceInvalidNormalizer
      - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - WordnetSynonymsGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: secondary
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - SecondaryMatcher
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: permute
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - PermuteGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: prefix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - PrefixGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: suffix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - SuffixGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: substring
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
    - LongNameNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - SubstringMatchGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: hyphens
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - HyphenGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: special-char-affix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - SpecialCharacterAffixGenerator
  filters:
    - SubnameFilter
#    - ValidNameFilter
-
  name: abbreviation
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - AbbreviationGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
-
  name: flag-affix
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - FlagAffixGenerator
  filters:
    - SubnameFilter
#    - ValidNameFilter
-
  name: leet
  normalizers:
    - StripEthNormalizer
    - UnicodeNormalizer
    - NamehashNormalizer
    - ReplaceInvalidNormalizer
  tokenizers:
    - WordNinjaTokenizer
  generators:
    - LeetGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
