generator:
  # the list of the domains, that are already registered
  domains: data/domains.head.csv
  # the query the names are generated for
  query: mydomain
  # the number of generated suggestions
  suggestions: 10
  pipelines:
    - 
      tokenizers:
        - BigramTokenizer
      generators:
        - WordnetSynonymsGenerator
      filters:
        - DomainFilter
filtering:
  # List of already registered domains
  domains: data/domains.head.csv
  root_path: ./
