app:
  input: query
  # the list of the domains, that are already registered
  domains: tests/data/domains.head.csv
  # the query the names are generated for
  query: mydomain
  # the number of generated suggestions (TODO: implement)
  suggestions: 10
  # the pipelines used to generate the suggestions
  # Make sure the required class is imported in generator/pipeline/pipeline.py
  pipelines:
    - 
      tokenizers:
        - BigramWordnetTokenizer
      generators:
        - WordnetSynonymsGenerator
      filters:
        - DomainFilter
        - ValidNameFilter
  categories: tests/data/categories/
  logging_level: INFO
# Configuration for the individual modules. So far all modules share the same config.
# This might be moved to the pipeline definition.
filtering:
  # List of already registered domains
  domains: tests/data/domains.head.csv
  root_path: ./
tokenization:
  dictionary: /usr/share/dict/words
generation:
  word2vec_model: glove-twitter-25
  suffixes_path: tests/data/suffixes.txt
  prefixes_path: tests/data/prefixes.txt
