defaults:
  - pipelines: test_new
  - _self_
# Configuration for the individual modules. So far all modules share the same config.
# This might be moved to the pipeline definition.
app:
  # read input from argument (query) or stdin
  input: query
  # the list of the domains, that are already registered
  domains: tests/data/suggestable_domains.csv
  # the query the names are generated for
  query: mydomain
  # the number of generated suggestions (TODO: implement)
  suggestions: 10
  # the pipelines used to generate the suggestions
  # Make sure the required class is imported in generator/pipeline/pipeline.py
  logging_level: INFO
# Configuration for the individual modules. So far all modules share the same config.
# This might be moved to the pipeline definition.
#  secondary_market_names: tests/data/secondary.csv
#  advertised_names: tests/data/advertised.csv
  internet_domains: tests/data/top_internet_names.csv
  primary_url: suggestable_domains.csv
#  secondary_url: secondary.csv
#  advertised_url: advertised.csv
  subnames_url: subnames.txt
  clubs_url: suggestable_clubs.csv
  clubs: tests/data/suggestable_clubs.csv
  #for longer names only first 30 characters are taken into consideration
  name_length_limit: 30
  min_available_fraction: 0.1
# if present, env variables will override values below
elasticsearch:
  scheme: ${oc.env:ES_SCHEME,https}
  host: ${oc.env:ES_HOST,localhost}
  port: ${oc.decode:${oc.env:ES_PORT,9243}}
  username: ${oc.env:ES_USERNAME,elastic}
  password: ${oc.env:ES_PASSWORD,password}
  index: ${oc.env:ES_INDEX,collection-templates} #TODO create a specific test index with a few test collections
  ltr:
    feature_store: ${oc.env:ES_LTR_FEATURE_STORE,ltr-metadata-index}
    feature_set: ${oc.env:ES_LTR_FEATURE_SET,ltr-feature-set}
    model_name: ${oc.env:ES_LTR_MODEL_NAME,exp6-8}
    window_size:
      instant: 20
      domain_detail: 100
filtering:
  # List of already registered domains
#  domains: tests/data/primary.csv
  subnames: tests/data/subnames.txt
  root_path: ./
tokenization:
  dictionary: tests/data/words.txt
  wordninja_dictionary: data/ngrams/wordninja_dictionary.txt.gz
  skip_one_letter_words: true
  skip_non_words: false
  add_letters_ias: true
  with_gaps: true
generation:
  word2vec_url: embeddings.pkl
  word2vec_path: data/embeddings.pkl
  suffixes_path: tests/data/suffixes.txt
  prefixes_path: tests/data/prefixes.txt
  name2emoji_path: tests/data/name2emoji.json
  name2symbol_path: tests/data/name2symbol.json
  limit: 10000
  empty_input_ability:
    - RandomAvailableNameGenerator
  generator_limits:
    HyphenGenerator: 128
    AbbreviationGenerator: 128
    EmojiGenerator: 150
    Wikipedia2VGenerator: 10
    RandomAvailableNameGenerator: 20000
  wikipedia2vec_url: enwiki_20180420_100d.processed.pkl
  wikipedia2vec_path: tests/data/wikipedia2vec.pkl
  person_name_affixes_path: data/person_name_affixes.json
  person_name_emojify_affixes_path: data/person_name_emojify_affixes.json
  person_name_expand_affixes_path: data/person_name_expand_affixes.json
  suffix2rhymes_path: data/suffix2rhymes.json
  grouping_categories:
    related:
      - CollectionGenerator
    wordplay:
      - AbbreviationGenerator
      - PermuteGenerator
      - HyphenGenerator
    alternates:
      - Wikipedia2VGenerator
      - W2VGenerator
      - WordnetSynonymsGenerator
    emojify:
      - EmojiGenerator
      - FlagAffixGenerator
      - KeycapGenerator
      - SymbolGenerator
    community:
      - SubstringMatchGenerator
      - OnSaleMatchGenerator
      - CategoriesGenerator
    expand:
      - PrefixGenerator
      - SuffixGenerator
      - SpecialCharacterAffixGenerator
      - RhymesGenerator
    gowild:
      - LeetGenerator
      - RandomAvailableNameGenerator
      - EasterEggGenerator
      - ReverseGenerator
    dynamic_:  # generator needs to implement get_grouping_category(output_name: str) method
      - PersonNameGenerator
  grouping_categories_order:
    - related
    - alternates
    - wordplay
    - emojify
    - community
    - expand
    - gowild
sorting:
  weighted_sampling:
    weights:
      HyphenGenerator: 1
      AbbreviationGenerator: 1
      EmojiGenerator: 1
      FlagAffixGenerator: 1
      PermuteGenerator: 1
      PrefixGenerator: 1
      SuffixGenerator: 1
      WordnetSynonymsGenerator: 1
      W2VGenerator: 1
      CategoriesGenerator: 1
      RandomAvailableNameGenerator: 1
      OnSaleMatchGenerator: 1
      Wikipedia2VGenerator: 1
      SpecialCharacterAffixGenerator: 1
      SubstringMatchGenerator: 1
      LeetGenerator: 1
      KeycapGenerator: 1
      CollectionGenerator: 1
random_available_name_pipeline:
  name: random
  generator: RandomAvailableNameGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter
person_names:
  firstnames_url: person_names_firstnames.json
  lastnames_url: person_names_lastnames.json
  other_url: person_names_other.json
  country_stats_url: person_names_country_stats.json
  country_bonus: 100
  firstnames_path: data/person_names_firstnames.json
  lastnames_path: data/person_names_lastnames.json
  other_path: data/person_names_other.json
  country_stats_path: data/person_names_country_stats.json
  country2langs_path: data/country2langs.json
ngrams:
  lazy_loading: true
  unigrams: data/ngrams/unigram_freq.csv
  bigrams: data/ngrams/bigram_freq.csv
  custom_dictionary: tests/data/ngrams/custom_dictionary.txt
  custom_token_frequency: 500000
collections:
  other_collections_path: data/collections_data/other_collections.json
  collections_limit: 3
  suggestions_limit: 10  # per one collections
  name_diversity_ratio: 0.5
  max_per_type: 2
