defaults:
  - pipelines: test
  - _self_
app:
  input: query
  # the list of the domains, that are already registered
  domains: tests/data/domains.head.csv
  # the query the names are generated for
  query: mydomain
  # the number of generated suggestions (TODO: implement)
  suggestions: 10
  # the pipelines used to generate the suggestions
  # Make sure the required class is imported in generator/pipeline/pipeline.py
  categories: tests/data/categories/
  categories_ignored: tests/data/categories/ignore.txt
  logging_level: INFO
# Configuration for the individual modules. So far all modules share the same config.
# This might be moved to the pipeline definition.
  secondary_market_names: tests/data/secondary.json
  advertised_names: tests/data/advertised.json
  internet_domains: tests/data/top_internet_names.txt
filtering:
  # List of already registered domains
  domains: tests/data/domains.head.csv
  subnames: tests/data/subnames.txt
  root_path: ./
tokenization:
  dictionary: tests/data/words.txt
generation:
  word2vec_model: glove-twitter-25
  suffixes_path: tests/data/suffixes.txt
  prefixes_path: tests/data/prefixes.txt
  limit: 10000
random_pipeline:
  normalizers:
    - StripEthNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - RandomGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter