defaults:
  - pipelines: test
  - _self_
app:
  input: query
  # the list of the domains, that are already registered
  domains: tests/data/primary.csv
  # the query the names are generated for
  query: mydomain
  # the number of generated suggestions (TODO: implement)
  suggestions: 10
  # the pipelines used to generate the suggestions
  # Make sure the required class is imported in generator/pipeline/pipeline.py
  logging_level: INFO
# Configuration for the individual modules. So far all modules share the same config.
# This might be moved to the pipeline definition.
  secondary_market_names: tests/data/secondary.csv
  advertised_names: tests/data/advertised.csv
  internet_domains: tests/data/top_internet_names.csv
  primary_url: https://namegen-orwjfodkfwefeewoi.s3.amazonaws.com/primary.csv
  secondary_url: https://namegen-orwjfodkfwefeewoi.s3.amazonaws.com/secondary.csv
  advertised_url: https://namegen-orwjfodkfwefeewoi.s3.amazonaws.com/advertised.csv
  subnames_url: https://namegen-orwjfodkfwefeewoi.s3.amazonaws.com/subnames.txt
  clubs_url: https://namegen-orwjfodkfwefeewoi.s3.amazonaws.com/clubs.csv
  clubs: tests/data/clubs.csv
filtering:
  # List of already registered domains
  domains: tests/data/primary.csv
  subnames: tests/data/subnames.txt
  root_path: ./
tokenization:
  dictionary: tests/data/words.txt
generation:
  word2vec_url: https://namegen-resources-dgpstnjyliwzhlhp.s3.amazonaws.com/embeddings.pkl
  word2vec_path: data/embeddings.pkl
  suffixes_path: tests/data/suffixes.txt
  prefixes_path: tests/data/prefixes.txt
  limit: 10000
  wikipedia2vec_url:
  wikipedia2vec_path: tests/data/wikipedia2vec.pkl
random_pipeline:
  normalizers:
    - StripEthNormalizer
  tokenizers:
    - NoneTokenizer
  generators:
    - RandomGenerator
  filters:
    - SubnameFilter
    - ValidNameFilter